Show user count in users page
MangoAutomation/ma-dashboards pull request #405
Opened 2021-09-29 19:54 UTC by jpuccinit

#RAD-1090

2021-09-30 17:02 UTC, terrypacker commented
@jpuccinit looks good to me, @jazdw you want to take a look at this?  If not I am fine to merge it.

2021-10-04 20:46 UTC, jazdw requested changes

2021-10-04 20:46 UTC, jazdw commented on UI/web-src/ngMango/components/userTable/userTable.html
> +                                        <span ma-tr="ui.app.outOf" ma-tr-args="[$ctrl.pages.$total]"></span>
Please avoid using translations for incomplete sentences. You should add a new translation for the complete sentence and use a single span.

2021-10-04 20:46 UTC, jazdw commented on UI/web-src/ngMango/components/userTable/userTable.html
> +                                                        ng-change="$ctrl.selectedColumnsChanged()"
Please avoid reformatting lines that have not been modified. This makes it really hard for me to look at and tell what you have actually changed.

2021-10-04 20:46 UTC, jazdw commented
@jpuccinit Please include a screenshot

2021-10-04 22:52 UTC, jpuccinit commented
<img width="1091" alt="Screen Shot 2021-10-04 at 5 32 41 PM" src="https://user-images.githubusercontent.com/9293586/135935086-2cc5b3cf-a699-45a2-9c5c-76716d191602.png">
<img width="1102" alt="Screen Shot 2021-10-04 at 5 32 54 PM" src="https://user-images.githubusercontent.com/9293586/135935109-96249631-ab5b-4ae0-8120-89611ae84157.png">

2021-10-05 17:06 UTC, jazdw commented
@jpuccinit thank you. However there are still a lot of whitespace changes which I do not want to merge, please revert the whitespace changes and squash all of your changes into one commit.

2021-10-05 17:07 UTC, jazdw requested changes
@jpuccinit thank you. However there are still a lot of whitespace changes which I do not want to merge, please revert the whitespace changes and squash all of your changes into one commit.

2021-10-05 17:08 UTC, jazdw commented on UI/resources/i18n.properties
> +ui.app.xItemsSelectedLongOutOf={0, plural, =0{No items} =1{1 item} other{# items}} selected out of {1}
Add parenthesis around "out of". e.g. `1 item selected (out of 3)`

2021-10-05 18:12 UTC, jpuccinit commented
@jazdw  I thing i fix  the whietespace problem

2021-10-05 19:21 UTC, jazdw approved these changes

2021-10-05 19:21 UTC, merged