PI-1939, PI-1940 - fix ui discrepancies on admin home and data sources page
MangoAutomation/ma-dashboards pull request #439
Opened 2023-03-25 07:55 UTC by montoresdennis

Before:
![image](https://user-images.githubusercontent.com/107421595/227704827-13c2e495-9110-4f99-9d30-a472595be3cc.png)
![image](https://user-images.githubusercontent.com/107421595/227704848-42977e18-2436-4979-a7a8-c3c02699af52.png)

After:
![image](https://user-images.githubusercontent.com/107421595/227704580-b607d89a-3e41-44ea-ad07-89d38fa8524d.png)
![image](https://user-images.githubusercontent.com/107421595/227704971-3b9dab78-773c-4a33-8e9f-94674c4a7084.png)

2023-03-27 21:28 UTC, pierpuccini approved these changes

2023-03-28 14:52 UTC, jazdw commented
@montoresdennis here's another problem, these two top bars should be different colors (they are in the dark theme). (open the date bar to see them both)
![image](https://user-images.githubusercontent.com/3579645/228278161-2bdd0e87-52e3-4f93-a29a-2e5373409d9f.png)

The theme names are also inconsistent, can you rename them to `piMangoDark` and `piMangoLight` (camel case)

2023-03-28 14:53 UTC, jazdw requested changes
See

2023-03-28 14:53 UTC, jazdw commented on UI/web-src/ngMango/piMango.css
> +    color: white;
Use a palette color if possible

2023-03-30 22:18 UTC, montoresdennis commented
> @montoresdennis here's another problem, these two top bars should be different colors (they are in the dark theme). (open the date bar to see them both) ![image](https://user-images.githubusercontent.com/3579645/228278161-2bdd0e87-52e3-4f93-a29a-2e5373409d9f.png)
> 
> The theme names are also inconsistent, can you rename them to `piMangoDark` and `piMangoLight` (camel case)

![image](https://user-images.githubusercontent.com/107421595/228976268-d8e3345d-ed31-4527-8d7b-8245495217db.png)

solved

2023-03-30 23:54 UTC, montoresdennis commented
@jazdw @greychrist Ok, I discussed the coloring stuff with Rosbely and this is the final result
![image](https://user-images.githubusercontent.com/107421595/228989667-9425459f-b57c-40ae-9463-8686b75527c9.png)

2023-03-31 18:04 UTC, merged

2023-03-31 19:26 UTC, greychrist commented
I love this.  Thanks!

On Thu, Mar 30, 2023 at 7:54 PM Dennis Montores ***@***.***>
wrote:

> @jazdw <https://github.com/jazdw> @greychrist
> <https://github.com/greychrist> Ok, I discussed the coloring stuff with
> Rosbely and this is the final result
> [image: image]
> <https://user-images.githubusercontent.com/107421595/228989667-9425459f-b57c-40ae-9463-8686b75527c9.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MangoAutomation/ma-dashboards/pull/439#issuecomment-1491106258>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFBX5JNIJNRGVWDU4XR2F6LW6YMMDANCNFSM6AAAAAAWHMFGZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>